---
- hosts: all
  tasks:
  - name: install firewalld
    yum: name=firewalld state=present
    become: yes

  - name: firewall rules
    firewalld:
      permanent: yes
      immediate: yes
      service: "{{ item }}"
      state: enabled
    with_items:
      - http
      - https
    become: yes


  - name: restart service firewalld
    service:
      name: firewalld
      state: restarted
    become: yes
